const GET_USER = 'GET_USER'
const UPDATE_USER_FILTER = 'UPDATE_USER_FILTER'
const UPDATE_USER_SORT = 'UPDATE_USER_SORT'
const UPDATE_PAGIANTION_FILTER = 'UPDATE_PAGIANTION_FILTER'

export {
  GET_USER, UPDATE_USER_FILTER, UPDATE_USER_SORT, UPDATE_PAGIANTION_FILTER
}
