const GET_USER = 'GET_USER';
const UPDATE_USER_FILTER = 'UPDATE_USER_FILTER';
const UPDATE_PAGINATION_FILTER = 'UPDATE_PAGINATION_FILTER';

export { GET_USER, UPDATE_USER_FILTER, UPDATE_PAGINATION_FILTER };
