const FETCH_USERS = 'FETCH_USERS'
const UPDATE_USER_FILTER = 'UPDATE_USER_FILTER'
const UPDATE_USER_SORT = 'UPDATE_USER_SORT'
const UPDATE_PAGIANTION_FILTER = 'UPDATE_PAGIANTION_FILTER'

export {
  FETCH_USERS, UPDATE_USER_FILTER, UPDATE_USER_SORT, UPDATE_PAGIANTION_FILTER
}
