const SET_USER = 'SET_USER'
const SET_USER_SORT = 'SET_USER_SORT'
const SET_PAGINATION_FILTER = 'SET_PAGINATION_FILTER'
const SET_USER_QUERY = 'SET_USER_QUERY'
const SET_ERROR = 'SET_ERROR'
const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES'
const SET_IS_LOADING = 'SET_IS_LOADING'

export {
  SET_USER,
  SET_USER_SORT,
  SET_PAGINATION_FILTER,
  SET_USER_QUERY,
  SET_ERROR,
  SET_TOTAL_PAGES,
  SET_IS_LOADING
}
