const GET_USER = 'GET_USER';
const SET_USER = 'SET_USER';
const UPDATE_USER_FILTER = 'UPDATE_USER_FILTER';
const SET_USER_SORT = 'SET_USER_SORT';
const UPDATE_PAGINATION_FILTER = 'UPDATE_PAGINATION_FILTER';
const UPDATE_USER_QUERY = 'UPDATE_USER_QUERY';
const SET_PAGINATION_FILTER = 'SET_PAGINATION_FILTER';

export {
  GET_USER,
  UPDATE_USER_FILTER,
  SET_USER,
  UPDATE_PAGINATION_FILTER,
  UPDATE_USER_QUERY,
  SET_USER_SORT,
  SET_PAGINATION_FILTER,
};
