const SET_USER = 'SET_USER';
const SET_USER_SORT = 'SET_USER_SORT';
const SET_PAGINATION_FILTER = 'SET_PAGINATION_FILTER';
const SET_USER_QUERY = 'SET_USER_QUERY';

export {
  SET_USER, SET_USER_SORT, SET_PAGINATION_FILTER, SET_USER_QUERY,
};
