const SET_QUESTIONS = 'SET_QUESTIONS';
const SET_QUESTION_SORT = 'SET_QUESTION_SORT';
const SET_PAGINATION_FILTER = 'SET_PAGINATION_FILTER';
const SET_QUESTION_QUERY = 'SET_USER_QUERY';

export {
  SET_QUESTIONS, SET_QUESTION_SORT, SET_PAGINATION_FILTER, SET_QUESTION_QUERY,
};
